import{A as j}from"./assets/vendor-CTqzIL4Y.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const g of r.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&d(g)}).observe(document,{childList:!0,subtree:!0});function c(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=c(t);fetch(t.href,r)}})();const u=[{picture:"../img/my-projects/myprojects-1.png",text:"power pulse webservice"},{picture:"../img/my-projects/myprojects-2.png",text:"mimino website"},{picture:"../img/my-projects/myprojects-3.png",text:"vyshyvanka vibes Landing"},{picture:"../img/my-projects/myprojects-4.png",text:"green harvest online store"},{picture:"../img/my-projects/myprojects-5.png",text:"wallet webservice"},{picture:"../img/my-projects/myprojects-6.png",text:"chego jewelry website"},{picture:"../img/my-projects/myprojects-7.png",text:"energy flow webservice"},{picture:"../img/my-projects/myprojects-8.png",text:"fruitbox online store"},{picture:"../img/my-projects/myprojects-9.png",text:"English excellence webservice"},{picture:"../img/my-projects/myprojects-10.png",text:"starlight studio landing page"}],f=document.querySelector(".myprojects-list-galery"),a=document.querySelector(".myprojects-button-load"),b="https://github.com/Iryna-Shenenko/Hermes";let n=3;function v(e){return e.map(o=>`
    <li class="myprojects-gallery-item">
    <div>
          <img class="myprojects-photo-card" src="${o.picture}" alt="${o.text}" />
        </div>
        <div class="myprojects-subtitle">
          <p class="myprojects-subtitle-text">React, JavaScript, Node JS, Git</p>
          <div class="myprojects-info">
            <h3 class="myprojects-info-title">${o.text}</h3>
            <a href="${b}">
            <button class="myprojects-info-button">visit
                <svg width="24" height="24">
                        <use href="../img/my-projects/myprojects.svg#icon-visit"></use>
                </svg>
            </button>
            </a>
        </div>
    </div>
    </li>
  `).join("")}function S(){const e=u.slice(0,n);f.innerHTML=v(e)}function x(){const e=a.querySelector("span");e&&(e.textContent="Loading..."),a.disabled=!0,setTimeout(()=>{const o=u.length-n,c=o>=3?3:o;n+=c;const d=u.slice(n-c,n);f.insertAdjacentHTML("beforeend",v(d)),e&&(e.textContent="Load More"),a.disabled=!1,n>=u.length&&(a.style.display="none")},1e3)}S();a.addEventListener("click",x);new j(".accordion-container");const s={light:"light-theme",dark:"dark-theme"},L=document.querySelector(".theme-switch__toggle"),i=document.querySelector(".menu-header"),l=document.querySelector("body"),p=localStorage.getItem("theme");p?(l.classList.add(p),i.classList.add(p)):(l.classList.add(s.light),i.classList.add(s.light));p===s.dark&&(L.checked=!0);const w=e=>{e.currentTarget.checked?(l.classList.remove(s.light),l.classList.add(s.dark),i.classList.remove(s.light),i.classList.add(s.dark),localStorage.setItem("theme",s.dark)):(l.classList.remove(s.dark),l.classList.add(s.light),i.classList.remove(s.dark),i.classList.add(s.light),localStorage.setItem("theme",s.light))};L.addEventListener("change",w);const y=document.querySelector(".open-header-menu-button"),h=document.querySelector(".close-button"),m=document.querySelector(".menu-header"),I=document.querySelectorAll(".menu-header-link");y&&m&&y.addEventListener("click",function(){m.classList.add("is-open")});h&&m&&h.addEventListener("click",function(){m.classList.remove("is-open")});I.forEach(e=>{e.addEventListener("click",function(o){o.preventDefault();const c=document.querySelector(this.getAttribute("href"));c&&c.scrollIntoView({behavior:"smooth"}),m.classList.remove("is-open")})});document.querySelector(".email-input");document.querySelector(".message-text");const q=document.querySelector(".contact-btn");q.addEventListener("submit",k);function k(e){e.preventDefault(),e.target.elements}
//# sourceMappingURL=index.js.map
