import{A as x,S as E,N as q,P as I,a as P}from"./assets/vendor-D8AQ2Jog.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&c(y)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const p=[{picture:"../img/my-projects/myprojects-1.png",text:"power pulse webservice"},{picture:"../img/my-projects/myprojects-2.png",text:"mimino website"},{picture:"../img/my-projects/myprojects-3.png",text:"vyshyvanka vibes Landing"},{picture:"../img/my-projects/myprojects-4.png",text:"green harvest online store"},{picture:"../img/my-projects/myprojects-5.png",text:"wallet webservice"},{picture:"../img/my-projects/myprojects-6.png",text:"chego jewelry website"},{picture:"../img/my-projects/myprojects-7.png",text:"energy flow webservice"},{picture:"../img/my-projects/myprojects-8.png",text:"fruitbox online store"},{picture:"../img/my-projects/myprojects-9.png",text:"English excellence webservice"},{picture:"../img/my-projects/myprojects-10.png",text:"starlight studio landing page"}],L=document.querySelector(".myprojects-list-galery"),u=document.querySelector(".myprojects-button-load"),M="https://github.com/Iryna-Shenenko/Hermes";let a=3;function j(e){return e.map(t=>`
    <li class="myprojects-gallery-item">
    <div>
          <img class="myprojects-photo-card" src="${t.picture}" alt="${t.text}" />
        </div>
        <div class="myprojects-subtitle">
          <p class="myprojects-subtitle-text">React, JavaScript, Node JS, Git</p>
          <div class="myprojects-info">
            <h3 class="myprojects-info-title">${t.text}</h3>
            <a href="${M}">
            <button class="myprojects-info-button">visit
                <svg width="24" height="24">
                        <use href="../img/my-projects/myprojects.svg#icon-visit"></use>
                </svg>
            </button>
            </a>
        </div>
    </div>
    </li>
  `).join("")}function A(){const e=p.slice(0,a);L.innerHTML=j(e)}function C(){const e=u.querySelector("span");e&&(e.textContent="Loading..."),u.disabled=!0,setTimeout(()=>{const t=p.length-a,i=t>=3?3:t;a+=i;const c=p.slice(a-i,a);L.insertAdjacentHTML("beforeend",j(c)),e&&(e.textContent="Load More"),u.disabled=!1,a>=p.length&&(u.style.display="none")},1e3)}A();u.addEventListener("click",C);new x(".accordion-container");const s={light:"light-theme",dark:"dark-theme"},S=document.querySelector(".theme-switch__toggle"),l=document.querySelector(".menu-header"),d=document.querySelector("body"),g=localStorage.getItem("theme");g?(d.classList.add(g),l.classList.add(g)):(d.classList.add(s.light),l.classList.add(s.light));g===s.dark&&(S.checked=!0);const B=e=>{e.currentTarget.checked?(d.classList.remove(s.light),d.classList.add(s.dark),l.classList.remove(s.light),l.classList.add(s.dark),localStorage.setItem("theme",s.dark)):(d.classList.remove(s.dark),d.classList.add(s.light),l.classList.remove(s.dark),l.classList.add(s.light),localStorage.setItem("theme",s.light))};S.addEventListener("change",B);const v=document.querySelector(".open-header-menu-button"),w=document.querySelector(".close-button"),m=document.querySelector(".menu-header"),N=document.querySelectorAll(".menu-header-link");v&&m&&v.addEventListener("click",function(){m.classList.add("is-open")});w&&m&&w.addEventListener("click",function(){m.classList.remove("is-open")});N.forEach(e=>{e.addEventListener("click",function(t){t.preventDefault();const i=document.querySelector(this.getAttribute("href"));i&&i.scrollIntoView({behavior:"smooth"}),m.classList.remove("is-open")})});document.querySelector(".email-input");document.querySelector(".message-text");const V=document.querySelector(".contact-btn");V.addEventListener("submit",$);function $(e){e.preventDefault(),e.target.elements}const O=document.querySelector(".reviews-list"),T=document.querySelector("#reviews"),H=document.querySelector(".reviews-title"),f={mobile:320,tablet:768,desktop:1280};let h=!1,b=!1;const n=new E(".swiper",{modules:[q,I],navigation:{nextEl:".nav-arrow-next",prevEl:".nav-arrow-prev",enabled:!0},keyboard:{enabled:!0}});k();async function R(){try{const e=await P.get("https://portfolio-js.b.goit.study/api/reviews");if(e.status===200){const t=await _(e);O.insertAdjacentHTML("beforeend",t),n.update()}else h=!0}catch(e){console.error("Error fetching reviews:",e),h=!0}}async function _(e){return e.data.map(t=>{const{author:i,avatar_url:c,review:r}=t;return`
        <li class="swiper-slide reviews-wrap">
          <div class="reviews-item">
            <p class="reviews-text">${r}</p>
            <div class="reviews-credentials">
              <img class="reviews-img" src="${c}" alt="${i}" />
              <p class="reviews-author">${i}</p>
            </div>
          </div>
        </li>`}).join("")}function D(){const e=T.getBoundingClientRect();e.top<window.innerHeight&&e.bottom>0&&h&&!b&&(J("Not found"),b=!0)}function J(e){H.textContent=e,alert("An error occurred while fetching reviews. Please try again later.")}window.addEventListener("scroll",D);R();function k(){const e=window.innerWidth;e<f.tablet||e>f.tablet&&e<f.desktop?n.params.slidesPerView=1:(n.params.slidesPerView=2,n.params.spaceBetween=24),n.update()}document.querySelector(".nav-arrow-prev").addEventListener("keydown",e=>{(e.key==="Enter"||e.key===" ")&&n.slidePrev()});document.querySelector(".nav-arrow-next").addEventListener("keydown",e=>{(e.key==="Enter"||e.key===" ")&&n.slideNext()});window.addEventListener("resize",k);
//# sourceMappingURL=index.js.map
